export const AUTH_USER = "AUTH_USER";

export const ADD_PROJECT = "ADD_PROJECT";
export const SET_PRIORITY_PROJECT = "SET_PRIORITY_PROJECT";
export const SET_LATEST_PROJECT = "SET_LATEST_PROJECT";
export const UPDATE_PRIORITY_PROJECT = "UPDATE_PRIORITY_PROJECT";
export const UPDATE_RECENT_PROJECT = "UPDATE_RECENT_PROJECT";
export const SET_ALL_PROJECT = "SET_ALL_PROJECT";
